---
abstract: 'addon plugin that adds functionality to let users reset passwords'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-UserLogin-ForgotPassword
requires:
  App::ZofCMS::Plugin::Base: 0
  DBI: 1.607
  Digest::MD5: 2.36_01
  HTML::Template: 2.9
  MIME::Lite: 3.027
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/App-ZofCMS-Plugin-UserLogin-ForgotPassword/issues
  repository: git://github.com/zoffixznet/App-ZofCMS-Plugin-UserLogin-ForgotPassword.git
version: 1.001001
